// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTrials = Integer.parseInt(args[0]);
		int count = 0;
		for (int i = 0; i < nTrials; i++) {
			if (Math.random() > 0.5) {
				count++;
			}
		}
		System.out.println("> 0.5:  " + count + " times");
		System.out.println("<= 0.5: " + (nTrials - count) + " times");
		if (count < nTrials) {
			System.out.println("Ratio:  " + (count + 0.0) / (nTrials - count));
		}
	}
}