trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'cs-intro-chatbot'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Your-Azure-Container-Registry'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Your-Azure-Subscription'
    appName: 'Your-App-Service-Name'
    containers: '$(imageName):$(Build.BuildId)'
