steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs-intro-chatbot/app', '.']
images:
- 'gcr.io/cs-intro-chatbot/app'
steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'deploy', 'app', '--image', 'gcr.io/cs-intro-chatbot/app', '--region', 'us-central1', '--platform', 'managed']
  args: ['run', 'deploy', 'app', '--image', 'gcr.io/cs-intro-chatbot/app', '--region', 'us-central1', '--platform', 'managed']